### PR TITLE
Fix for page load causes 403 request (#2363)

### LINKED ISSUE #2363: Login page load causes 403 request
When one is not logged in, accessing the motionEye web interface causes an AJAX request which is doomed to fail with a 403, as, we are not logged in yet. This request should be prevented in the first place:
```
GET http://192.168.1.23:8765/login/?_=1647363420707&_username=_&_signature=63a7bcae23f66d6e066f9ac091a802163fcf12c4 403 (Forbidden)
jquery.min.js?v=0.43.0:5
send @ jquery.min.js?v=0.43.0:5
ajax @ jquery.min.js?v=0.43.0:5
ajax @ main.js?v=0.43.0:478
(anonymous) @ main.js?v=0.43.0:5352
c @ jquery.min.js?v=0.43.0:3
fireWith @ jquery.min.js?v=0.43.0:3
ready @ jquery.min.js?v=0.43.0:3
q @ jquery.min.js?v=0.43.0:3
```
The call is done here: https://github.com/motioneye-project/motioneye/blob/2df0383/motioneye/static/js/main.js#L5352
Looks like it is always tried to load the current config. We should find a way to do that only when we have a valid session. From what I found, the username cookie contains `_` when not logged in, or this is a dummy value shown by my browser when the content is empty. However, if there is no username, the login request for receiving configs must fail, so we shouldn't attempt it. Similarly refreshing camera frames can be skipped then.

### PR DESCRIPTION
**Pull request by tunkio**
Fix #2363 

Now logout will erase password cookie too. Previously it stayed active for 10 years. Because of this you could set proper username for username cookie and system let you in. 

I removed default _ value for username in a cookie. Hopefully this won't break something what I didn't see.

We are still using sha1 hashes for password. These are broken and should be fixed.
We are storing sha1 password hash in  a cookie(for 10 years).  Should we use tokens instead?

### CODE REVIEW

File: motioneye/static/js/main.js [hunk 1]
```diff
@@ -528,10 +528,25 @@ function showErrorMessage(message) {
 }
 
 function doLogout() {
-    setCookie(USERNAME_COOKIE, '_');
+    setCookie(USERNAME_COOKIE, '');
+    setCookie(PASSWORD_COOKIE, '');
     window.location.reload(true);
 }
 
+function isAuthCookiesSet() {
```
Comment (MichaIng) [inline motioneye/static/js/main.js:536]: Since it's two cookies, plural 😛 (while I know that `is` is a pretty nice prefix for functions returning boolean values, so feel free to ignore my grammatical comment 😅):
```suggestion
function AreAuthCookiesSet() {
```

**Comment by MichaIng** [comment]
Looks very good, and I cannot imagine that the emptied password cookie would cause any issues: On every first/new client login it's the same condition.

> We are still using sha1 hashes for password. These are broken and should be fixed.

Totally agreed. We just need a migration plan. We could migrate to e.g. SHA512 but keep SHA1 as fallback for checking the password. It should be possible to derive the hashing algorithm based on hash length. We could then force users to re-set passwords when the current password is hashed with SHA1, so that we can remove the fallback some versions later. However, a task for a dedicated PR, of course.

> We are storing sha1 password hash in a cookie(for 10 years). Should we use tokens instead?

Would be better, I agree, but let's do that in a dedicated PR as well.

**Review by MichaIng — APPROVED** [review]

**Comment by tunkio** [comment]
I emptied username too. Before that was set to _. I tried to think why, maybe because empty cookie will vanish when you close the browser. Well this can cause something or not.
